### ISSUE TITLE
Integrate Track number into translated path, if present

### ISSUE THREAD

**Issue by deingithub** [nunner/mufs#3]
i.e. `[root]/Artist/Album/01 - First Track That Happens To Start With A Letter That's Not A`

**Comment by nunner** [comment]
I think that this would cause some issues with renaming the files, as renaming a file changes the title tag of a file. How will we know when we added/removed/changed a track number and when we just want to change the title?

**Comment by deingithub** [comment]
We could just add the convention that `[0-9]+ - ` at the beginning of the file name indicates track number and parse accordingly (how many titles do start with digits and a dash in that pattern?)

**Comment by nunner** [comment]
Sounds like a solid plan. I think this should be regulated through a config file though, as not everyone will like this (probably)
