### ISSUE TITLE
Allow for custom folder structure via command line args

### ISSUE THREAD

**Issue by deingithub** [nunner/mufs#7]
Change the command line form to `mufs [args] [root] [mountpoint] [structure]`, where `[structure]` is a format-string-like template for the folder structure.
This would allow great customizability with just a few format tokens, such as `%t` for **t**itles, `%f` for albums ("**f**rom"), `%a` for **a**rtists, `%n` for track **n**umbers, and maybe `%g` for **g**enres.

The default configuration, when no `[structure]` is provided, would mirror the current setup with `%a/%f/%t`.

Examples:
```
%a/%f/%t       => This Winter Machine/The Man Who Never Was/Fractured
%a - %f/%n %t  => Los Campesinos! - Romance Is Boring/01 In Medias Res
%g/%a - %t     => Progressive Rock/Thank You Scientist - Psychopomp
```

**Comment by nunner** [comment]
While this is certainly a big project, I think that this should also be controlled through the config file referenced in #3. I will look into this as soon as I have fixed #3.

**Comment by deingithub** [comment]
I personally see greater utility in having multiple differently structured mounts, or changing the ordering on the fly, which would be somewhat annoying when editing a config file instead of command line flags :p

**Comment by nunner** [comment]
Hm, you certainly have a point. Do you think I should drop the config file altogether, or just not use it for this?

**Comment by deingithub** [comment]
Depends - if we use this mechanism to implement #3 from the beginning, I believe there'd be little need for one?

**Comment by nunner** [comment]
Alright, I will implement it through command-line arguments, then.
